version = 1

[[analyzers]]
name = "php"

  [analyzers.meta]
  bootstrap_files = ["4"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["angular"]
  environment = [
    "nodejs",
    "jquery"
  ]